### ISSUE TITLE
Future of this project?

### ISSUE THREAD

**Issue by redoc123** [egorzot/vue-form-generator-element#1]
I am interested in using this and contributing to this project. Do you have any interest in working on it?

**Comment by egorzot** [comment]
Hi @redoc123 !
Yes but I'm working on it as necessary. 
Any way your PR's is welcome!

**Comment by morris821028** [comment]
I also want to contribute to this project. But, I don't know how to test this repo with the current config. There are some undefined variables in vue files. Does it work independently?

If we fork the origin repo and create some theme options, may it be better?

Here is an example https://github.com/morris821028/vue-form-generator/tree/master/examples/simple-element


![vue-form-generator-element-ui](https://user-images.githubusercontent.com/4697855/46723146-b8fe1a00-cca9-11e8-9800-19d9b5085444.PNG)

**Comment by egorzot** [comment]
@morris821028 Sorry, but I can't build your example. 
Can you give the link to the docs for theme options? Due to [this](https://github.com/vue-generators/vue-form-generator/issues/262) issue there are no ways to create fields with other css framework except creation our custom fields.

**Comment by morris821028** [comment]
@egorzot  I know the bootstrap framework limited the html structure. However, element-ui is different from bootstrap.

```
git clone https://github.com/morris821028/vue-form-generator
cd vue-form-generator
npm install 
npm run build:core
```

And then, open the folder /examples/simple-element/index.html in your browser.

We can add theme field in formOptions, like https://github.com/morris821028/vue-form-generator/blob/master/examples/simple-element/main.js#L154

```
formOptions: {
  validateAfterLoad: true,
  validateAfterChanged: true,
  theme: 'element', // default is bootstrap
  labelWidth: "100, // add some field for special element-ui form
```

It just a proposal. Creating a custom field is still a workaround. And then, we won't change the type name in future, use a mapping instead of written field.type directly.

**Comment by egorzot** [comment]
@morris821028 so you suggest to create fork and maintain it? 
I can whip into shape this repo and add tests but I need some time. But I think that new forked repo is not good idea.

**Comment by morris821028** [comment]
@egorzot  I'm a frontend beginner.  Could we have the template syntax to define html structure? That is, through the options.

If it works, perhaps give the official pull request to do that. Do you have any idea?

**Comment by egorzot** [comment]
I'm not sure that including element-ui dependency in vue-form-generator repository is good idea. 
This project is set of custom components that extend the last one that's why it's not a fork.
So if you want to improve this project your PR is welcome.

**Comment by redoc123** [comment]
I am trying to do a jquery type drag and drop to generate schema. If you have time we can collab and make a decent form builder UI and schema. It would be of great help to community. 

What do you say?. (Sorry for late response. I missed update on this thread)

It would be nice if you could improve documentation of current code especially mentioning whats not stable. Give a rough roadmap as you see it.

<img width="1173" alt="screen shot 2018-12-22 at 8 47 55 am" src="https://user-images.githubusercontent.com/4265968/50370119-d4997100-05c6-11e9-9953-f16adc49e70d.png">

**Comment by egorzot** [comment]
Hi @redoc123 ! Sorry for long response :)
I'll try to fully refactor this project on NY holidays and  release a stable version.
`I am trying to do a jquery type drag and drop to generate schema.`
It would be nice but what about generator based on vue stack?

**Comment by redoc123** [comment]
Thanks for response.
It would be completely based on vue stack. I am giving jquery form builder as a visual reference. 

You can start with making a running example of this to begin with.

**Comment by redoc123** [comment]
I started from scratch and got something like this working. Did nt do it properly with proper abstraction  but it seems to do the job for me. I will publish to npm as soon as I have it tested.

https://drive.google.com/file/d/1khSPeJwsRglwyEoz-0m4_69i1Wlu4wFG/view
